"""pump charactericstic model

Revision ID: 2feefdf01979
Revises: 95a9c25f3ebc
Create Date: 2017-05-13 21:27:34.454748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2feefdf01979'
down_revision = '95a9c25f3ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('Q_H_polynom', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('Q_EFF_polynom', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('Q_PWR_polynom', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('Q_NPSHr_polynom', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('EFFmax', sa.Float(precision=2), nullable=True),
    sa.Column('Qbep', sa.Float(precision=2), nullable=True),
    sa.Column('Hbep', sa.Float(precision=2), nullable=True),
    sa.Column('PWRbep', sa.Float(precision=2), nullable=True),
    sa.Column('PWR2bep', sa.Float(precision=2), nullable=True),
    sa.Column('NPSHrbep', sa.Float(precision=2), nullable=True),
    sa.Column('_Qmin', sa.Float(precision=2), nullable=True),
    sa.Column('_Qmax', sa.Float(precision=2), nullable=True),
    sa.Column('Hmin', sa.Float(precision=2), nullable=True),
    sa.Column('Hmax', sa.Float(precision=2), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=True),
    sa.Column('enters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_characteristic')
    # ### end Alembic commands ###
