"""motors

Revision ID: 31cec8434d74
Revises: 98d37994c0c6
Create Date: 2017-03-06 22:32:53.098449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cec8434d74'
down_revision = '98d37994c0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('power', sa.Float(precision=2), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('current_frequency', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('_ip_protection', sa.String(length=2), nullable=True),
    sa.Column('explosion_protected', sa.Boolean(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['motor_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motor')
    # ### end Alembic commands ###
