"""pump model

Revision ID: 95a9c25f3ebc
Revises: 31cec8434d74
Create Date: 2017-05-13 20:38:48.764053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a9c25f3ebc'
down_revision = '31cec8434d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('size_type', sa.String(length=80), nullable=True),
    sa.Column('inbound_diameter', sa.Float(precision=2), nullable=True),
    sa.Column('inbound_pressure', sa.Float(precision=2), nullable=True),
    sa.Column('outbound_diameter', sa.Float(precision=2), nullable=True),
    sa.Column('outbound_pressure', sa.Float(precision=2), nullable=True),
    sa.Column('seal_type', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('material_body', sa.Integer(), nullable=True),
    sa.Column('material_wheel', sa.Integer(), nullable=True),
    sa.Column('material_shaft', sa.Integer(), nullable=True),
    sa.Column('max_pressure', sa.Float(precision=2), nullable=True),
    sa.Column('frequency_regulation_needed', sa.Boolean(), nullable=True),
    sa.Column('fluid_temp_min', sa.Integer(), nullable=True),
    sa.Column('fluid_temp_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['pump_manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('motor', sa.Column('frequency_regulation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motor', 'frequency_regulation')
    op.drop_table('pump')
    # ### end Alembic commands ###
